# Generated by Django 4.0.4 on 2022-05-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeusername',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
